# Stage 1: build and compile
FROM node:16-alpine3.11 as build-stage
 
WORKDIR /usr/src/app
 
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json .
 
# Install app dependencies
RUN npm i
 
# Bundle app source
COPY . .

CMD [ "npm", "start" ]
EXPOSE 4200